version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3 